id: 28ee9a09a7bc41d39de288f5271fdacb
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_99-The_Blessed_One%27s_Wisdom_That_Leads_to_Infinite_Certainty-v2
  language: bo
  author: ''
  volume: {}
